# Generated by Django 3.1.2 on 2020-11-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_tasks_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='points',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
