# Generated by Django 3.1.2 on 2020-11-12 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_tasks_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedtasks',
            name='completed_task_ss',
            field=models.ImageField(upload_to='completed_task_ss/'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='task_ss',
            field=models.ImageField(upload_to='task_ss/'),
        ),
        migrations.DeleteModel(
            name='PointsClaimed',
        ),
    ]
